### ISSUE TITLE
HttpError: Label does not exist

### ISSUE THREAD

**Issue by KeziahMoselle** [github/issue-labeler#20]
Hello,

I'm trying to debug an issue i'm having using this action and my labels are created.

If you have any idea why i'm getting this error please !
It would be really appreciated 🙏🏽
Thank you

here is the logs :

```
Warning: Unexpected input(s) 'enable-versioned-regex', valid inputs are ['repo-token', 'configuration-path']
Run github/issue-labeler@v2.0
(node:2480) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
Removing label ✨ Lightning from issue #1
    at /home/runner/work/_actions/github/issue-labeler/v2.0/node_modules/@octokit/request/dist-node/index.js:66:23
Removing label 🔥 Normal from issue #1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Removing label ☀️ Long from issue #1
(node:2480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Removing label ⏱️ Durée libre from issue #1
(node:2480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2480) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.0/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2480) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.0/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2480) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.0/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

`.github/labeler.yml`

```
'✨ Lightning':
  - '- [x] 5 minutes'
'🔥 Normal':
  - '- [x] 20 minutes'
'☀️ Long':
  - '- [x] 30 minutes'
'⏱️ Durée libre':
  - '- [x] Précisez :'
```

`.github/workflows/labeler.yml`

```
name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
```

My labels exists in the repository :
![image](https://user-images.githubusercontent.com/9168097/99150254-729ef480-2693-11eb-82ee-235c0d3772ae.png)

Repository link if you need it : https://github.com/StrasbourgJS/talks

**Comment by edimitchel** [comment]
Hi,
Problem solved by escaping brackets using `\` !

May be, an enhancement here could be made on the deprecation you can see in the logs !
