### ISSUE TITLE
New feature: Create label if it does not exist

### ISSUE THREAD

**Issue by dgteixeira** [github/issue-labeler#28]
When I try to put up a non-existent label, I get the following error:

```
(node:1680) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.4/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1680) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.4/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1680) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.4/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1680) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.4/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:1680) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.4/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:1680) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.4/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:1680) UnhandledPromiseRejectionWarning: HttpError: Label does not exist
    at /home/runner/work/_actions/github/issue-labeler/v2.4/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
```

There should be a flag to force the creation of the label.
Is this possible?

**Comment by dgteixeira** [comment]
Not enough testing caused this.
Sorry, closing the issue.
